# =============================================================================
# KeyMagic — Makefile
# =============================================================================

PROJECT   := KeyMagic.xcodeproj
SCHEME    := KeyMagic
BUILD_DIR := build

# Notarization credentials — set via environment or override on the command line:
#   make dist NOTARIZE_TEAM_ID=3FKXTCP8JU NOTARIZE_APPLE_ID=you@example.com NOTARIZE_PASSWORD=@keychain:AC_PASSWORD
NOTARIZE_TEAM_ID   ?= 3FKXTCP8JU
NOTARIZE_APPLE_ID  ?=
NOTARIZE_PASSWORD  ?=

# Local package reference UUID (deterministic — generated by XcodeGen from project.yml)
PKG_REF_UUID := C9F4A7C64EE4F53F0F15D17D

# Detect xcbeautify for prettier xcodebuild output; fall back to cat
XCBEAUTIFY := $(shell command -v xcbeautify 2>/dev/null)
PRETTY     := $(if $(XCBEAUTIFY), | xcbeautify,)

# Re-export PATH so brew-installed tools are found when invoked via Xcode run scripts
export PATH := /opt/homebrew/bin:/usr/local/bin:$(PATH)

.DEFAULT_GOAL := help

.PHONY: help setup gen open \
        build release \
        test uitest test-all \
        format lint \
        archive export notarize dist \
        clean reset \
        ci

# -----------------------------------------------------------------------------
# Help
# -----------------------------------------------------------------------------

help: ## Show available targets
	@echo ""
	@echo "  KeyMagic"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	    | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'
	@echo ""

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------

setup: ## Install required tools and generate Xcode project
	@echo "→ Checking tools..."
	@command -v xcodegen   >/dev/null || (echo "  Installing xcodegen..."   && brew install xcodegen)
	@command -v swift-format >/dev/null || (echo "  Installing swift-format..." && brew install swift-format)
	@command -v xcbeautify >/dev/null || (echo "  Installing xcbeautify..." && brew install xcbeautify)
	@echo "  ✓ xcodegen   $$(xcodegen version)"
	@echo "  ✓ swift-format $$(swift-format --version 2>&1)"
	@echo "  ✓ xcbeautify $$(xcbeautify --version 2>&1)"
	@echo ""
	@$(MAKE) gen

# -----------------------------------------------------------------------------
# Project generation
# -----------------------------------------------------------------------------

# XcodeGen 2.x omits the required `package` back-reference in
# XCSwiftPackageProductDependency for local packages — patch it after every
# generate so Xcode can resolve KeyMagicKit.
_patch-pbxproj:
	@perl -i -p0e \
	    's/(isa = XCSwiftPackageProductDependency;\n)(\t+productName = KeyMagicKit;)/$$1\t\t\tpackage = $(PKG_REF_UUID) \/* XCLocalSwiftPackageReference "." *\/;\n$$2/' \
	    $(PROJECT)/project.pbxproj
	@echo "  ✓ patched XCSwiftPackageProductDependency"

gen: ## Regenerate Xcode project from project.yml (run after editing project.yml)
	@echo "→ Generating Xcode project..."
	xcodegen generate
	@$(MAKE) --no-print-directory _patch-pbxproj

open: gen ## Regenerate and open project in Xcode
	open $(PROJECT)

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

build: ## Build app — Debug (via xcodebuild)
	@echo "→ Building (Debug)..."
	xcodebuild build \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -configuration Debug \
	    -derivedDataPath $(BUILD_DIR) \
	    ONLY_ACTIVE_ARCH=YES \
	    $(PRETTY)

release: ## Build app — Release (via xcodebuild)
	@echo "→ Building (Release)..."
	xcodebuild build \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -configuration Release \
	    -derivedDataPath $(BUILD_DIR) \
	    $(PRETTY)

run: ## Build (Debug) and run app from the CLI
	@$(MAKE) --no-print-directory build
	@echo "→ Launching app..."
	@APP_PATH="$(BUILD_DIR)/Build/Products/Debug/KeyMagic.app"; \
	if [ -d "$$APP_PATH" ]; then \
	    open "$$APP_PATH"; \
	else \
	    BIN="$$APP_PATH/Contents/MacOS/KeyMagic"; \
	    if [ -x "$$BIN" ]; then \
	        exec "$$BIN"; \
	    else \
	        echo "  ! Could not find app at $$APP_PATH"; exit 1; \
	    fi \
	fi

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

test: ## Run unit tests via swift test (fast, no Xcode needed)
	@echo "→ Running unit tests..."
	swift test --configuration debug

uitest: ## Run UI tests via xcodebuild
	@echo "→ Running UI tests..."
	xcodebuild test \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -only-testing:KeyMagicUITests \
	    -derivedDataPath $(BUILD_DIR) \
	    ONLY_ACTIVE_ARCH=YES \
	    $(PRETTY)

test-all: test uitest ## Run all tests (unit + UI)

# -----------------------------------------------------------------------------
# Code quality
# -----------------------------------------------------------------------------

format: ## Auto-format all Swift source files with swift-format
	@echo "→ Formatting..."
	swift-format format --in-place --recursive Sources Tests
	@echo "  ✓ done"

lint: ## Lint Swift source files with swift-format (no writes)
	@echo "→ Linting..."
	swift-format lint --recursive Sources Tests
	@echo "  ✓ done"

# -----------------------------------------------------------------------------
# Archive / Release
# -----------------------------------------------------------------------------

ARCHIVE_PATH        := $(BUILD_DIR)/$(SCHEME).xcarchive
EXPORT_PATH         := $(BUILD_DIR)/export
EXPORT_OPTIONS_PLIST := Resources/exportOptions.plist

archive: ## Create a Release archive (.xcarchive) signed with Developer ID
	@echo "→ Archiving..."
	xcodebuild archive \
	    -project     $(PROJECT) \
	    -scheme      $(SCHEME) \
	    -configuration Release \
	    -archivePath $(ARCHIVE_PATH) \
	    $(PRETTY)
	@echo "  ✓ archive: $(ARCHIVE_PATH)"

export: archive ## Export archive as a Developer ID-signed .app ready for notarization
	@echo "→ Exporting..."
	xcodebuild -exportArchive \
	    -archivePath      $(ARCHIVE_PATH) \
	    -exportPath       $(EXPORT_PATH) \
	    -exportOptionsPlist $(EXPORT_OPTIONS_PLIST) \
	    $(PRETTY)
	@echo "  ✓ exported: $(EXPORT_PATH)/$(SCHEME).app"

notarize: ## Submit exported .app to Apple Notary Service and staple the ticket
	@[ -n "$(NOTARIZE_APPLE_ID)" ] || (echo "  ! Set NOTARIZE_APPLE_ID (e.g. you@example.com)"; exit 1)
	@[ -n "$(NOTARIZE_PASSWORD)" ] || (echo "  ! Set NOTARIZE_PASSWORD (e.g. @keychain:AC_PASSWORD)"; exit 1)
	@echo "→ Notarizing..."
	@# Zip the .app for submission (notarytool accepts .zip, .dmg, or .pkg)
	ditto -c -k --keepParent "$(EXPORT_PATH)/$(SCHEME).app" "$(EXPORT_PATH)/$(SCHEME).zip"
	xcrun notarytool submit "$(EXPORT_PATH)/$(SCHEME).zip" \
	    --apple-id  "$(NOTARIZE_APPLE_ID)" \
	    --password  "$(NOTARIZE_PASSWORD)" \
	    --team-id   "$(NOTARIZE_TEAM_ID)" \
	    --wait
	@echo "→ Stapling notarization ticket..."
	xcrun stapler staple "$(EXPORT_PATH)/$(SCHEME).app"
	@echo "  ✓ notarized and stapled: $(EXPORT_PATH)/$(SCHEME).app"

dist: export notarize ## Full distribution pipeline: archive → export → notarize → staple
	@echo "  ✓ Distribution build ready: $(EXPORT_PATH)/$(SCHEME).app"

# -----------------------------------------------------------------------------
# Clean
# -----------------------------------------------------------------------------

clean: ## Remove build artifacts (keeps .xcodeproj)
	@echo "→ Cleaning build artifacts..."
	rm -rf $(BUILD_DIR)
	swift package clean
	@echo "  ✓ done"

reset: clean ## Full reset — also removes .xcodeproj (run 'make gen' afterwards)
	@echo "→ Removing generated project..."
	rm -rf $(PROJECT)
	@echo "  ✓ done. Run 'make gen' to regenerate."

# -----------------------------------------------------------------------------
# CI
# -----------------------------------------------------------------------------

ci: ## Full CI pipeline: lint → unit tests → release build
	@echo "========================================="
	@echo "  KeyMagic CI Pipeline"
	@echo "========================================="
	@echo ""
	@echo "--- lint ---"
	@$(MAKE) --no-print-directory lint
	@echo ""
	@echo "--- unit tests ---"
	@$(MAKE) --no-print-directory test
	@echo ""
	@echo "--- release build ---"
	@$(MAKE) --no-print-directory release
	@echo ""
	@echo "========================================="
	@echo "  ✓ CI passed"
	@echo "========================================="